
INSERT INTO CUSTOMER(CUSTOMER_ID, NAME) VALUES(1, 'Customer 1');
INSERT INTO ACCOUNT(ACCOUNT_ID, BALANCE, CUSTOMER_CUSTOMER_ID) VALUES(1, 1000, 1);

INSERT INTO CUSTOMER(CUSTOMER_ID, NAME) VALUES(2, 'Customer 2');
INSERT INTO ACCOUNT(ACCOUNT_ID, BALANCE, CUSTOMER_CUSTOMER_ID) VALUES(2, 1500, 2);

INSERT INTO CUSTOMER(CUSTOMER_ID, NAME) VALUES(3, 'Customer 3');
INSERT INTO ACCOUNT(ACCOUNT_ID, BALANCE, CUSTOMER_CUSTOMER_ID) VALUES(3, 2300, 3);

INSERT INTO CUSTOMER(CUSTOMER_ID, NAME) VALUES(4, 'Customer 4');
INSERT INTO ACCOUNT(ACCOUNT_ID, BALANCE, CUSTOMER_CUSTOMER_ID) VALUES(4, 900, 4);

INSERT INTO CUSTOMER(CUSTOMER_ID, NAME) VALUES(5, 'Customer 5');
INSERT INTO ACCOUNT(ACCOUNT_ID, BALANCE, CUSTOMER_CUSTOMER_ID) VALUES(5, 1800, 5);